spring:
  application:
    name: MailSender
  profiles:
    include:
      - mail
      - oauth

server:
  servlet:
    session:
      cookie:
        same-site: None
        secure: true
  forward-headers-strategy: framework

app:
  cors:
    allowed-origins:
      - "http://localhost:8081"
